steps
- name: 'gcr.io/cloud-builders/docker'
  args: ['image', 'build', '-t', 'gcr.io/$PROJECT_ID/flaskapp:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['image', 'push', 'gcr.io/$PROJECT_ID/flaskapp:$SHORT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - '$_APP_NAME'
  - '--image'
  - 'gcr.io/$PROJECT_ID/flaskapp:$SHORT_SHA'
  - '--region'
  - 'us-central1'
  - '--unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _APP_NAME: flaskapp
